# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Información del proyecto
site_name: Docmarx
site_url: https://farid-nl.github.io/docmarx/
edit_uri: edit/main/docs/

# Información del repositorio
repo_url: https://github.com/farid-nl/docmarx
repo_name: farid-nl/docmarx

# Copyright

# Configuración
theme:
  logo: assets/logo.png
  name: material
  language: es
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.action.edit
    - content.action.view
    #- content.code.select
    - navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    #- navigation.path
    #- navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    #- toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Cambiar a modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a preferencia del sistema
  font:
    text: Nunito
    code: JetBrains Mono
  icon:
    tag:
      php: simple/php
      c: simple/c
      cs: material/language-csharp
      cpp: simple/cplusplus
      javascript: simple/javascript
      java: fontawesome/brands/java
      python: simple/python
      angular: simple/angular
      vul-alta: material/alert
      vul-media: material/alert
      vul-baja: material/alert

# Plugins
plugins:
  - tags
  - search
  #- typeset
  #- privacy

# Hooks

# Configuración adicional
extra:
  tags:
    PHP: php
    C: c
    C#: cs
    C++: cpp
    Javascript: javascript
    Java: java
    Python: python
    Angular: angular
    Alta: vul-alta
    Media: vul-media
    Baja: vul-baja

extra_css:
  - stylesheets/extra.css

# Extensiones
#   • Code blocks
#   • Annotations
#   • Admonitions
#   • Content tabs
#   • BetterEm
markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      #linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
        - name: html+php
          lang: php
          options:
            startinline: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

# Navegación
nav:
  - Docmarx: index.md
  - PHP:
      - Client Privacy Violation: php/client-privacy-violation.md
      - Deprecated Functions: php/deprecated-functions.md
      - Error Messages Misconfiguration: php/error-messages-misconfiguration.md
      - Improper Exception Handling: php/improper-exception-handling.md
      - Information Exposure Through an Error Message: php/information-exposure-through-an-error-message.md
      - Insufficient Sanitization for XSS: php/insufficient-sanitization-for-xss.md
      - Log Forging: php/log-forging.md
      - Missing Framing Policy: php/missing-framing-policy.md
      - Potential Clickjacking on Legacy Browsers: php/potential-clickjacking-on-legacy-browsers.md
      - Reflected XSS: php/reflected-xss.md
      - SSRF: php/ssrf.md
      - Session Fixation: php/session-fixation.md
      - Trust Boundary Violation in Session Variables: php/trust-boundary-violation-in-session-variables.md
      - Unchecked Input for Loop Condition: php/unchecked-input-for-loop-condition.md
  - C++:
      - Dangerous Functions: cpp/dangerous-functions.md
      - Unchecked Return Value: cpp/unchecked-return-value.md
  - Javascript:
      - Client DOM Open Redirect: js/client-dom-open-redirect.md
      - Client DOM Stored XSS: js/client-dom-stored-xss.md
      - Client JQuery Deprecated Symbols: js/client-jquery-deprecated-symbols.md
      - Client Potential XSS: js/client-potential-xss.md
